-- MySQL Script generated by MySQL Workbench
-- Sun Jun 12 13:05:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema smartlist
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `smartlist` ;

-- -----------------------------------------------------
-- Schema smartlist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smartlist` DEFAULT CHARACTER SET utf8 ;
USE `smartlist` ;

-- -----------------------------------------------------
-- Table `smartlist`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartlist`.`produto` ;

CREATE TABLE IF NOT EXISTS `smartlist`.`produto` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `peso` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartlist`.`lista_compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartlist`.`lista_compras` ;

CREATE TABLE IF NOT EXISTS `smartlist`.`lista_compras` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartlist`.`lista_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartlist`.`lista_produto` ;

CREATE TABLE IF NOT EXISTS `smartlist`.`lista_produto` (
  `id_lista_compra` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `valor_transporte` DOUBLE NULL,
  CONSTRAINT `lista`
    FOREIGN KEY (`id_lista_compra`)
    REFERENCES `smartlist`.`lista_compras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `produto_listado`
    FOREIGN KEY (`id_produto`)
    REFERENCES `smartlist`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `lista_idx` ON `smartlist`.`lista_produto` (`id_lista_compra` ASC) VISIBLE;

CREATE INDEX `produto_idx` ON `smartlist`.`lista_produto` (`id_produto` ASC) INVISIBLE;


-- -----------------------------------------------------
-- Table `smartlist`.`estabelecimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartlist`.`estabelecimento` ;

CREATE TABLE IF NOT EXISTS `smartlist`.`estabelecimento` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `latitude` BIGINT NOT NULL,
  `longitude` BIGINT NOT NULL,
  `url_imagem` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartlist`.`produto_estabelecimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartlist`.`produto_estabelecimento` ;

CREATE TABLE IF NOT EXISTS `smartlist`.`produto_estabelecimento` (
  `id_produto` INT NOT NULL,
  `id_estabelecimento` INT NOT NULL,
  `preco` DOUBLE NOT NULL,
  CONSTRAINT `produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `smartlist`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `estabelecimento`
    FOREIGN KEY (`id_estabelecimento`)
    REFERENCES `smartlist`.`estabelecimento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `produto_idx` ON `smartlist`.`produto_estabelecimento` (`id_produto` ASC) VISIBLE;

CREATE INDEX `estabelecimento_idx` ON `smartlist`.`produto_estabelecimento` (`id_estabelecimento` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
